language: r
r:
  - release
  - devel
cache: packages
sudo: required

matrix:
  include:
    - python:3.6

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_binary_packages:
 - jsonlite
 - R6

