language: r
r:
  - release
  - devel
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_packages:
  - rjson
  - R6
  - knitr

before_install:
  - sudo apt-get install python-singledispatch
