language: r
r:
  - release
  - devel
sudo: required

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_binary_packages:
  - rjson
  - R6

before_install:
  - sudo apt-get install python-singledispatch
